Repository wonbi92/ios-wanted-GyroData, pull requests merged in 2023-01, with the labels that each got.

#21 feat: CoreData Model 및 MotionMO Entity 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/GyroData.xcdatamodeld/GyroData.xcdatamodel/contents
  GyroData/Repository/CoreData/Entity/MotionMO+CoreDataClass.swift
  GyroData/Repository/CoreData/Entity/MotionMO+CoreDataProperties.swift
Labels: ⚙️Feature

#22 feat: MotionDTO 구조체 구현 및 Codable, Identifiable 채택
  GyroData.xcodeproj/project.pbxproj
  GyroData/Repository/FileManager/Entity/MotionDTO.swift
Labels: ⚙️Feature

#24 Motion 구조체 및 MotionDataType 프로토콜 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Entity/Motion.swift
  GyroData/Domain/Utility/CMAcceleration+.swift
  GyroData/Domain/Utility/CMRotationRate+.swift
  GyroData/Domain/Utility/MotionDataType.swift
Labels: ⚙️Feature, Wonbi

#23 feat: Repository Protocol 구현
  GyroData/Repository/Protocol/Repository.swift
Labels: ⚙️Feature, Ayaan

#27 Default Core Data Repository 구현
  GyroData/Repository/CoreData/DefaultCoreDataRepository.swift
  GyroData/Repository/CoreData/Protocol/CoreDataRepository.swift
Labels: ⚙️Feature, 🛠Refactor, Wonbi

#26 FileManagerRepository Protocol 및 DefaultFileManagerRepository 구현
  GyroData/Repository/FileManager/DefaultFileManagerRepository.swift
  GyroData/Repository/FileManager/Entity/MotionDTO.swift
  GyroData/Repository/FileManager/Protocol/FileManagerRepository.swift
Labels: ⚙️Feature, 🛠Refactor, Ayaan
