Repository wonbi92/ios-wanted-GyroData, pull requests merged in 2023-02, with the labels that each got.

#30 FileManagerRepository 비동기 구현
  GyroData/Repository/FileManager/DefaultFileManagerRepository.swift
  GyroData/Repository/FileManager/Protocol/FileManagerRepository.swift
Labels: 🛠Refactor, Ayaan

#31 Default Core Data Repository 리팩토링
  GyroData/Repository/CoreData/DefaultCoreDataRepository.swift
  GyroData/Repository/CoreData/Protocol/CoreDataRepository.swift
Labels: 🛠Refactor, Wonbi

#32 MotionDeletable 및 MotionDeleteService 구현
  GyroData/Domain/Service/MotionDeleteService.swift
  GyroData/Domain/Service/Protocol/MotionDeletable.swift
  GyroData/Repository/CoreData/DefaultCoreDataRepository.swift
  GyroData/Repository/CoreData/Protocol/CoreDataRepository.swift
Labels: ⚙️Feature, 🛠Refactor, Ayaan

#34 Motion creatable 프로토콜 및 MotionCreateService 구현
  GyroData/Domain/Entity/Motion.swift
  GyroData/Domain/Service/MotionCreateService.swift
  GyroData/Domain/Service/Protocol/MotionCreatable.swift
  GyroData/Repository/CoreData/DefaultCoreDataRepository.swift
  GyroData/Repository/CoreData/Protocol/CoreDataRepository.swift
  GyroData/Repository/FileManager/DefaultFileManagerRepository.swift
  GyroData/Repository/FileManager/Protocol/FileManagerRepository.swift
Labels: ⚙️Feature, 🛠Refactor, Wonbi

#35 FileManagerMotionReadService 및 FileManagerMotionReadable Protocol 구현
  GyroData/Domain/Service/FileManagerMotionReadService.swift
  GyroData/Domain/Service/Protocol/FileManagerMotionReadable.swift
Labels: ⚙️Feature, Ayaan

#37 CoreDataMotionReadable 프로토콜 및 CoreDataMotionReadService 구현
  GyroData/Domain/Service/CoreDataMotionReadService.swift
  GyroData/Domain/Service/Protocol/CoreDataMotionReadable.swift
Labels: ⚙️Feature, Wonbi

#41 MotionDeleteService 테스트 케이스 추가
  GyroDataTests/ServiceTests/MotionDeleteServiceTests.swift
Labels: 🔬Test, Wonbi

#42 FileManagerMotionReadService 테스트 케이스 추가
  GyroDataTests/ServiceTests/Common/FileManagerRepositoryMock.swift
  GyroDataTests/ServiceTests/FileManagerMotionReadServiceTests.swift
Labels: 🔬Test, Wonbi

#40 CoreDataMotionReadService Test Case 추가
  GyroDataTests/ServiceTests/CoreDataMotionReadServiceTests.swift
Labels: 🔬Test, Ayaan

#39 MotionCreateService Test Case 추가
  GyroDataTests/ServiceTests/MotionCreateServiceTests.swift
Labels: 🔬Test, Ayaan

#46 MotionMeasurementService 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Service/MotionMeasurementService.swift
  GyroData/Domain/Service/Protocol/MotionMeasurable.swift
Labels: ⚙️Feature, Ayaan, P0

#47 MotionMeasureViewModel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Scene/MotionMeasure/MotionMeasureViewModel.swift
  GyroData/Scene/Utility/AlertFactory/AlertStlye.swift
Labels: ⚙️Feature, 🛠Refactor, Ayaan

#45 MotionsListViewModel 구현
  GyroData/Domain/Service/CoreDataMotionReadService.swift
  GyroData/Domain/Service/Protocol/CoreDataMotionReadable.swift
  GyroData/Repository/CoreData/DefaultCoreDataRepository.swift
  GyroData/Repository/CoreData/Protocol/CoreDataRepository.swift
  GyroData/Scene/MotionsList/MotionsListViewModel.swift
Labels: ⚙️Feature, 🛠Refactor, Wonbi

#48 MotionViewModel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Scene/Motion/MotionGraphViewController.swift
  GyroData/Scene/Motion/MotionPlayViewController.swift
  GyroData/Scene/Motion/MotionViewModel.swift
  GyroData/Scene/MotionGraph/MotionGraphViewModel.swift
  GyroData/Scene/MotionPlay/MotionPlayViewModel.swift
Labels: ⚙️Feature, 🛠Refactor, Wonbi

#57 MeasurementViewController 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Service/MotionMeasurementService.swift
  GyroData/Domain/Service/Protocol/MotionMeasurable.swift
  GyroData/Scene/MotionMeasure/MotionMeasureViewController.swift
  GyroData/Scene/MotionMeasure/MotionMeasureViewModel.swift
  GyroData/Scene/Utility/Date+.swift
Labels: ⚙️Feature, 🛠Refactor, Ayaan

#59 MotionsListViewController 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Domain/Entity/Motion.swift
  GyroData/Scene/MotionsList/MotionCell.swift
  GyroData/Scene/MotionsList/MotionsListViewController.swift
  GyroData/Scene/MotionsList/MotionsListViewModel.swift
  GyroData/SceneDelegate.swift
Labels: ⚙️Feature, 🛠Refactor, Wonbi
